FROM jenkins/jenkins:lts

# Install Python
USER root
RUN apt-get update && apt-get install -y python3 python3-pip

# Set default Python version to Python 3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

USER jenkins
